### ISSUE TITLE
Some things I found

### ISSUE THREAD

**Issue by laurenstacho** [UTK-geog415-s15/UTK-geog415-s15.github.io#1]
Hi!
I found just a couple things:
1. the R code for a trial has r x <- 2+2 , but I think you meant "in r": x <- 2+2
2. The default for cloning (at least on my computer) is the HTTP, not the SSH, so I cloned it wrong and it worked fine, so I didn't know it was wrong until I tried to push my commits to github from R and it kept giving me a fatal error. This might not be a problem for other people, but a heads up about which cloning you use might be helpful. 
3. When you change the README.MD file in R, it won't let you commit anything until you've saved the file. Again, a simple thing, but it might be something that hangs people up.
4. I haven't figured out how to do anything yet from the GitHub app that we installed for a previous step, so I've just been doing everything in R or through the github website. The interface for macs is kind of sparse, so I'm still playing around with it.
Best,
Lauren

**Comment by nnnagle** [comment]
Done.
